openapi: "3.0.2"
info:
  title: "OTA_Server API"
  description: "OTA_Server API"
  version: "1.0.0"
servers:
- url: "https://OTA_Server"
paths:
  /api/v0.0.1/firmware:
    get:
      description: ""
      parameters:
      - name: "device-id"
        in: "header"
        required: false
        schema:
          type: "string"